name: Github Release

on:
    push:
        tags:
            - 'v*.*.*'
jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v2
              with:
                  version: latest
                  args: release --rm-dist --skip-validate
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
